version: '3'
services:

  eventstore:
    image: eventstore/eventstore:release-4.1.1
    restart: always
    ports:
      - "2113:2113"
      - "1113:1113"
    logging:
      driver: "none"

  mongodb:
    image: mongo:4
    restart: always
    #volumes:
    #  - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    #  MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: dockers_mongodb_1
    depends_on:
      - mongodb
    logging:
      driver: "none"
